server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: lambda
    cloudwatchlogs:
      region: us-east-1
      log_group_names:
        - /aws/lambda/analytics-ingestor
      use_incoming_timestamp: true